### PR TITLE
Don't reallocate pcre2_match_data for every exec, you just need it once in comp

### PR DESCRIPTION
**Pull request by avar**
See the linked mailing list thread on the second patch. This presumably makes things faster, maybe my use of malloc/free here should be amended to use some xmalloc/perl malloc function.

### CODE REVIEW

**Comment by rurban** [comment]
Yes, this is how we should do it.
I already started with something like that in Hyperscan.

We also need a 2nd compiled pcre2_code in pprivate for ascii/utf8 matches. The compiler doesn't know if the pattern will be used in ascii or utf8 context, so it will make a guess, and recompile if the code is missing. See #15

**Comment by rurban** [comment]
See the match-data-comp-alloc branch, and https://github.com/rurban/re-engine-PCRE2/issues/19
There is one regression with t/perl/regexp.t 1840

**Comment by avar** [comment]
@rurban Yeah no idea what that regression is about. FWIW I tested this on 5.14.0, ancient, I know. I don't have time to debug this, just hacked this up since it seemed like an easy win. So just closing this request since it has a regression, but maybe the idea can be salvaged in some other form.

**Comment by avar** [comment]
On a closer look this seems to be a general issue with re::engine::PCRE2's bugs related to mixed UTF8 & non-UTF8 patterns. Maybe it's worth merging this after all, since there's still a bunch of regressions related to that, and this one extra failure will be fixed when the general bug is fixed, i.e. we'll have both UTF-8 & non-UTF-8 pattern & match data in the pprivate struct & switch between them in some cases.

**Comment by rurban** [comment]
I keep it as proper branch, and I'm investigating. Strange side effect.

**Comment by rurban** [comment]
Yes, most likely. I'm looking into how study is implemented today

**Pull request closed without merging**
